from __future__ import annotations

from datetime import datetime
from io import BytesIO
import os
from pathlib import Path
import textwrap
from typing import Iterable

_mpl_dir = Path("/tmp/mplconfig")
_mpl_dir.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(_mpl_dir))
os.environ.setdefault("XDG_CACHE_HOME", "/tmp")

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.patches import FancyBboxPatch

from app.models.schemas import PipelineResponse


class PDFReportService:
    def build_pdf(
        self,
        analysis: PipelineResponse,
        portal: str,
        document_type: str,
        generated_by: str,
    ) -> bytes:
        buffer = BytesIO()
        generated_at = datetime.now().strftime("%d %b %Y, %I:%M %p")

        with PdfPages(buffer) as pdf:
            pdf.savefig(
                self._cover_page(
                    analysis=analysis,
                    portal=portal,
                    document_type=document_type,
                    generated_by=generated_by,
                    generated_at=generated_at,
                ),
                bbox_inches="tight",
            )
            plt.close("all")

            pdf.savefig(self._analysis_page(analysis), bbox_inches="tight")
            plt.close("all")

            pdf.savefig(self._report_page(analysis), bbox_inches="tight")
            plt.close("all")

        buffer.seek(0)
        return buffer.getvalue()

    def _cover_page(
        self,
        analysis: PipelineResponse,
        portal: str,
        document_type: str,
        generated_by: str,
        generated_at: str,
    ):
        fig = plt.figure(figsize=(8.27, 11.69), facecolor="#f7f0e6")
        ax = fig.add_axes([0, 0, 1, 1])
        ax.axis("off")

        ax.add_patch(
            FancyBboxPatch(
                (0.06, 0.06),
                0.88,
                0.88,
                boxstyle="round,pad=0.02,rounding_size=0.03",
                facecolor="#fffaf2",
                edgecolor="#d8cdbb",
                linewidth=1.2,
            )
        )
        ax.add_patch(
            FancyBboxPatch(
                (0.08, 0.72),
                0.84,
                0.18,
                boxstyle="round,pad=0.02,rounding_size=0.03",
                facecolor="#0f6653",
                edgecolor="#0f6653",
            )
        )

        fig.text(0.11, 0.85, "Regulatory Workflow Automation", fontsize=24, color="white", weight="bold")
        fig.text(0.11, 0.81, "Reviewer Support PDF Report", fontsize=13, color="#d8f0e8")
        fig.text(0.11, 0.76, analysis.report.report.title, fontsize=18, color="white", weight="bold")

        meta = [
            f"Portal: {portal}",
            f"Document Type: {document_type.replace('_', ' ').title()}",
            f"Report Generation Date: {generated_at}",
            f"Generated By: {generated_by}",
            f"Reviewer Support Mode: Enabled",
        ]
        y = 0.66
        for item in meta:
            fig.text(0.12, y, item, fontsize=11.5, color="#1e2a26")
            y -= 0.055

        highlight = [
            ("Risk Level", analysis.report.report.risk_level.upper()),
            ("Completeness", f"{analysis.validation.completeness_score}/100"),
            ("Suggested Severity", analysis.classification.predicted_label),
            ("Potential Duplicates", str(len(analysis.deduplication.duplicates))),
        ]
        x_positions = [0.12, 0.33, 0.54, 0.75]
        for (label, value), x in zip(highlight, x_positions):
            ax.add_patch(
                FancyBboxPatch(
                    (x - 0.015, 0.36),
                    0.17,
                    0.12,
                    boxstyle="round,pad=0.012,rounding_size=0.02",
                    facecolor="#f2f7f4",
                    edgecolor="#dbe6e0",
                )
            )
            fig.text(x, 0.485, label, fontsize=9, color="#60716c")
            fig.text(x, 0.405, value, fontsize=18, color="#0f6653", weight="bold")

        sensitive = analysis.anonymization
        fig.text(0.12, 0.25, "Sensitive Data Handling", fontsize=15, color="#bc6a33", weight="bold")
        sensitive_lines = [
            f"Detected entities: {len(sensitive.entities)}",
            f"Compliance tags: {', '.join(sensitive.compliance_tags)}",
            "Personal and health-related identifiers were processed through de-identification and irreversible anonymisation stages.",
            "This output is intended for reviewer support and should not replace official medical or regulatory judgment.",
        ]
        y = 0.215
        for line in sensitive_lines:
            fig.text(0.12, y, "\n".join(textwrap.wrap(line, width=82)), fontsize=10.5, color="#1e2a26")
            y -= 0.045

        return fig

    def _analysis_page(self, analysis: PipelineResponse):
        fig = plt.figure(figsize=(8.27, 11.69), facecolor="#fffaf2")
        gs = fig.add_gridspec(3, 2, height_ratios=[1.0, 1.1, 1.5], hspace=0.34, wspace=0.28)

        ax_summary = fig.add_subplot(gs[0, :])
        ax_summary.axis("off")
        ax_summary.set_title("Analysis Highlights", loc="left", fontsize=18, color="#0f6653", pad=12, fontweight="bold")
        summary_text = self._bullet_text(
            analysis.report.report.summary[:5] or ["No summary points available."]
        )
        ax_summary.text(0, 0.95, summary_text, va="top", fontsize=11, color="#1e2a26")

        ax_comp = fig.add_subplot(gs[1, 0])
        ax_class = fig.add_subplot(gs[1, 1])
        ax_dup = fig.add_subplot(gs[2, 0])
        ax_note = fig.add_subplot(gs[2, 1])

        self._draw_completeness_gauge(ax_comp, analysis.validation.completeness_score)
        self._draw_classification_chart(ax_class, analysis)
        self._draw_duplicate_change_chart(ax_dup, analysis)
        self._draw_notes_panel(ax_note, analysis)
        return fig

    def _report_page(self, analysis: PipelineResponse):
        fig = plt.figure(figsize=(8.27, 11.69), facecolor="#fffaf2")
        ax = fig.add_axes([0, 0, 1, 1])
        ax.axis("off")

        fig.text(0.08, 0.95, "Formatted Draft Report", fontsize=20, color="#0f6653", weight="bold")

        sections = [
            ("Observations", analysis.report.report.observations),
            ("Reviewer Attention Points", analysis.report.report.violations),
            ("Recommendations", analysis.report.report.recommendations),
            ("Next Actions", analysis.report.report.next_actions),
        ]

        box_height = 0.145
        box_gap = 0.03
        y = 0.9
        for title, items in sections:
            ax.add_patch(
                FancyBboxPatch(
                    (0.07, y - box_height),
                    0.86,
                    box_height,
                    boxstyle="round,pad=0.012,rounding_size=0.02",
                    facecolor="#f8fbf8",
                    edgecolor="#dde8e1",
                )
            )
            fig.text(0.1, y - 0.03, title, fontsize=14, color="#bc6a33", weight="bold")
            wrapped = self._bullet_text(items[:4] or ["No items available."], width=70)
            fig.text(0.1, y - 0.065, wrapped, fontsize=9.8, color="#1e2a26", va="top")
            y -= box_height + box_gap

        fig.text(0.08, 0.12, "Anonymized Narrative Extract", fontsize=14, color="#0f6653", weight="bold")
        excerpt = "\n".join(textwrap.wrap(analysis.anonymization.anonymized_text[:250], width=90))
        fig.text(0.08, 0.095, excerpt, fontsize=9.2, color="#33423d", va="top")
        return fig

    def _draw_completeness_gauge(self, ax, score: int) -> None:
        ax.set_title("Completeness Score", fontsize=14, color="#0f6653", fontweight="bold")
        ax.barh(["Score"], [100], color="#efe6d7")
        ax.barh(["Score"], [score], color="#0f6653")
        ax.set_xlim(0, 100)
        ax.set_xlabel("Percent")
        ax.text(min(score + 2, 95), 0, f"{score}%", va="center", fontsize=12, color="#1e2a26", fontweight="bold")
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.tick_params(axis="y", length=0)

    def _draw_classification_chart(self, ax, analysis: PipelineResponse) -> None:
        labels = [score.label for score in analysis.classification.scores]
        values = [round(score.score * 100, 1) for score in analysis.classification.scores]
        palette = ["#a43e31", "#b58310", "#0f6653", "#7a8781", "#4b6a88", "#af7d44"]
        colors = [palette[index % len(palette)] for index in range(len(labels))]
        ax.bar(labels, values, color=colors)
        ax.set_title("Suggested Severity Signals", fontsize=14, color="#0f6653", fontweight="bold")
        ax.set_ylim(0, max(max(values) + 10, 40))
        ax.set_ylabel("Support score %")
        ax.tick_params(axis="x", rotation=18)
        for idx, value in enumerate(values):
            ax.text(idx, value + 1.5, f"{value:.1f}%", ha="center", fontsize=10, color="#1e2a26")

    def _draw_duplicate_change_chart(self, ax, analysis: PipelineResponse) -> None:
        duplicates = len(analysis.deduplication.duplicates)
        if analysis.comparison:
            changes = analysis.comparison.change_summary
            values = [
                duplicates,
                changes["added_count"],
                changes["removed_count"],
                changes["modified_count"],
            ]
        else:
            values = [duplicates, 0, 0, 0]
        labels = ["Potential\nDuplicates", "Added", "Removed", "Modified"]
        colors = ["#bc6a33", "#58a98f", "#d48860", "#0f6653"]
        ax.set_title("Change and Similarity Snapshot", fontsize=14, color="#0f6653", fontweight="bold")
        total = sum(values)
        if total <= 0:
            ax.bar(labels, [0, 0, 0, 0], color=colors)
            ax.set_ylim(0, 1)
            ax.set_ylabel("Items")
            ax.text(1.5, 0.5, "No duplicates or version changes detected", ha="center", va="center", fontsize=11, color="#60716c")
            return
        ax.pie(values, labels=labels, colors=colors, autopct=lambda pct: f"{pct:.0f}%" if pct > 0 else "", startangle=90)

    def _draw_notes_panel(self, ax, analysis: PipelineResponse) -> None:
        ax.axis("off")
        ax.set_title("Reviewer Notes", fontsize=14, color="#0f6653", fontweight="bold", loc="left")
        notes = [
            f"Risk level assessed: {analysis.report.report.risk_level.title()}",
            f"OCR or extraction engine: {analysis.ocr.engine_used}",
            f"Entities masked: {len(analysis.anonymization.entities)}",
            f"Checklist reviewed: {analysis.validation.checklist_type.replace('_', ' ').title()}",
            f"Potential duplicates flagged: {len(analysis.deduplication.duplicates)}",
            "This PDF is a reviewer support artifact and should be validated by the assigned CDSCO officer.",
        ]
        ax.text(0, 0.95, self._bullet_text(notes, width=45), va="top", fontsize=11, color="#1e2a26")

    def _bullet_text(self, items: Iterable[str], width: int = 88) -> str:
        lines: list[str] = []
        for item in items:
            wrapped = textwrap.wrap(str(item), width=width) or [str(item)]
            lines.append(f"- {wrapped[0]}")
            for continuation in wrapped[1:]:
                lines.append(f"  {continuation}")
        return "\n".join(lines)
